# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(null=True, verbose_name='Descricao')),
                ('status', models.CharField(choices=[('P', 'Em Produção'), ('I', 'Em Implementação'), ('O', 'Obsoleto')], max_length=15, verbose_name='Status')),
                ('org_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacao.Organizacao')),
            ],
        ),
    ]
